-- create table players(
--     playerid serial PRIMARY KEY,
--     apiid integer unique,
--     name text not null,
--     team text,
--     position text,
--     shoots VARCHAR(1),
--     height_cm INTEGER,
--     weight_lbs INTEGER,
--     birth_date DATE
-- );

-- alter table reg_games
-- add column gamestatus text;

-- create table pre_games(
--     id bigint not null primary key,
--     "startTimeUTC" timestamp,
--     "homeTeam" varchar(255),
--     "awayTeam" varchar(255),
--     "homeScore" integer,
--     "awayScore" integer,
--     "gameState" text
-- );